### ISSUE TITLE
nvc++ compiler warning with -std=c++20 flag

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/spack-derecho#21]
When compiling the CUDA kernel in my C++ code, I got the following warning message:
```
nvcc warning : The -std=c++20 flag is not supported with the configured host compiler. Flag will be ignored.
```
This happens to both `nvhpc/23.7` and `nvhpc/24.3` versions on Derecho. I am using `cuda/12.2.1` for nvcc compiler.

**Comment by benkirk** [comment]
Since nvhpcngenerally relies on an underlying gcc, this isn’t surprising.
The system gcc-7.5.0 is being used behind the scenes and it doesn’t support
the newest c++ standards.

There are a few ways to have nvhpc use a newer gcc, of which we have
several. Brian might have some ideas for a path of least resistance
considering how things are tied together through spack.

I assume you need some c++20 functionality?

-Ben

**Comment by vanderwb** [comment]
I asked @sjsprecious to submit this following on from a Slack message he sent me. He is using our gcc-toolchain module to specify a newer GCC, but that isn't doing the trick for this use case. I am looking at what modifications need to happen there to make it work.

**Comment by sjsprecious** [comment]
Thanks @benkirk and @vanderwb for your comments. Yes, my C++ code is using some C++20 functionality, and thanks @vanderwb for working on this issue.

**Comment by vanderwb** [comment]
Confirmed fixed.
